version: "3.9"
services:
  express:
    build:
      context: ./
      dockerfile: Dockerfile
    image: express:latest
    ports:
      - 3000:3000
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - monogo_data:/data/db
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
volumes:
  monogo_data:
